//! Galois field GF(2^16) arithmetic for PAR2.
//!
//! PAR2 uses the primitive polynomial `x^16 + x^12 + x^3 + x + 1`, which fits in
//! 17 bits as `0x1100B`. Multiplication is implemented via log/antilog tables
//! seeded by the generator `α = 2`:
//!
//!   antilog[k] = α^k   (for k in 0..65535)
//!   log[α^k]   = k
//!   log[0]     = 65535 (sentinel — never the result of a real log)
//!
//! These tables are global, computed once on first use.

use std::sync::OnceLock;

pub const FIELD_BITS: u32 = 16;
pub const FIELD_COUNT: u32 = 1 << FIELD_BITS;
pub const FIELD_LIMIT: u32 = FIELD_COUNT - 1; // 65535 — the multiplicative order
pub const FIELD_GENERATOR: u32 = 0x1_100B; // PAR2's primitive polynomial

pub struct Gf16Tables {
    pub log: [u16; FIELD_COUNT as usize],
    pub antilog: [u16; FIELD_COUNT as usize],
}

/// Lazily-built global tables. The first call to `gf16_tables()` does ~64 KiB
/// of work and is cheap. The `Box` keeps the tables off the recursion stack
/// during initialisation; subsequent accesses go through a single pointer.
pub fn gf16_tables() -> &'static Gf16Tables {
    static TABLES: OnceLock<Box<Gf16Tables>> = OnceLock::new();
    TABLES.get_or_init(|| Box::new(build_tables()))
}

fn build_tables() -> Gf16Tables {
    let mut log = [0u16; FIELD_COUNT as usize];
    let mut antilog = [0u16; FIELD_COUNT as usize];

    let mut b: u32 = 1;
    for l in 0..FIELD_LIMIT {
        log[b as usize] = l as u16;
        antilog[l as usize] = b as u16;
        b <<= 1;
        if b & FIELD_COUNT != 0 {
            b ^= FIELD_GENERATOR;
        }
    }
    // Sentinel values: log(0) has no real answer (0 isn't generated by any α^k);
    // antilog(LIMIT) wraps back to 1 in a true cyclic group, but upstream stores 0
    // here so that `gf_pow(0, _)` falls through cleanly.
    log[0] = FIELD_LIMIT as u16;
    antilog[FIELD_LIMIT as usize] = 0;

    Gf16Tables { log, antilog }
}

/// Multiply two GF(2^16) elements. Both `a == 0` or `b == 0` yield 0.
#[inline]
pub fn gf_mul(a: u16, b: u16) -> u16 {
    if a == 0 || b == 0 {
        return 0;
    }
    let t = gf16_tables();
    let sum = t.log[a as usize] as u32 + t.log[b as usize] as u32;
    let idx = if sum >= FIELD_LIMIT {
        sum - FIELD_LIMIT
    } else {
        sum
    };
    t.antilog[idx as usize]
}

/// Raise `base` to a non-negative integer power. `0^0` is defined as 1
/// (matching upstream — this is the convention used when building the
/// Vandermonde RS matrix for an input column at exponent 0).
pub fn gf_pow(base: u16, exp: u32) -> u16 {
    if exp == 0 {
        return 1;
    }
    if base == 0 {
        return 0;
    }
    let t = gf16_tables();
    // log[base] * exp mod LIMIT, then antilog
    let log_base = t.log[base as usize] as u64;
    let prod = log_base * exp as u64;
    let reduced = (prod % FIELD_LIMIT as u64) as u32;
    t.antilog[reduced as usize]
}

/// Multiplicative inverse. Panics on `a == 0` (consistent with the upstream
/// `assert` in galois.h).
pub fn gf_inv(a: u16) -> u16 {
    assert!(a != 0, "GF(2^16) inverse of 0 is undefined");
    let t = gf16_tables();
    let log_a = t.log[a as usize] as u32;
    // (LIMIT - log_a) mod LIMIT — handles `a == 1` (log 0) where the inverse is
    // 1 itself; without the modulo we would hit the `antilog[LIMIT] == 0` sentinel.
    let log_inv = (FIELD_LIMIT - log_a) % FIELD_LIMIT;
    t.antilog[log_inv as usize]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_have_expected_sentinels() {
        let t = gf16_tables();
        assert_eq!(t.log[0], FIELD_LIMIT as u16);
        assert_eq!(t.antilog[0], 1, "α^0 == 1");
        assert_eq!(t.antilog[1], 2, "α^1 == 2 (generator α)");
    }

    #[test]
    fn multiplication_is_commutative_for_random_values() {
        // Walk a deterministic sequence so we touch many distinct elements.
        let mut state: u32 = 0xCAFEBABE;
        for _ in 0..2000 {
            state = state.wrapping_mul(2654435761).wrapping_add(1);
            let a = state as u16;
            let b = (state >> 16) as u16;
            assert_eq!(gf_mul(a, b), gf_mul(b, a), "a={a} b={b}");
        }
    }

    #[test]
    fn zero_annihilates() {
        for &x in &[1u16, 2, 0xABCD, 0xFFFF] {
            assert_eq!(gf_mul(0, x), 0);
            assert_eq!(gf_mul(x, 0), 0);
        }
    }

    #[test]
    fn multiplicative_identity() {
        for x in [1u16, 2, 3, 0x100, 0x1234, 0xFFFF] {
            assert_eq!(gf_mul(1, x), x);
            assert_eq!(gf_mul(x, 1), x);
        }
    }

    #[test]
    fn inverse_round_trips_for_every_nonzero_element() {
        // Sample heavily but not exhaustively for the unit test (full 65535 sweep
        // runs in a few milliseconds — keep it as a sanity check).
        for x in (1u16..=0xFFFF).step_by(7) {
            let inv = gf_inv(x);
            assert_eq!(gf_mul(x, inv), 1, "x={x}");
        }
    }

    #[test]
    fn pow_zero_is_one_for_any_base() {
        for base in [0u16, 1, 2, 0x1234, 0xFFFF] {
            assert_eq!(gf_pow(base, 0), 1);
        }
    }

    #[test]
    fn pow_of_zero_to_positive_is_zero() {
        for exp in [1u32, 2, 100, 65535] {
            assert_eq!(gf_pow(0, exp), 0);
        }
    }

    #[test]
    fn pow_matches_repeated_multiplication() {
        // α^k where α = 2 — should match antilog[k].
        let t = gf16_tables();
        for k in [0u32, 1, 2, 100, 1000, 65534] {
            assert_eq!(gf_pow(2, k), t.antilog[(k % FIELD_LIMIT) as usize]);
        }
    }

    #[test]
    fn pow_distributes_over_repeated_squaring() {
        // (a^2)^3 == a^6
        for a in [1u16, 3, 0x1111, 0xFFFE] {
            let a2 = gf_mul(a, a);
            let lhs = gf_mul(gf_mul(a2, a2), a2);
            let rhs = gf_pow(a, 6);
            assert_eq!(lhs, rhs, "a={a}");
        }
    }
}
